### ISSUE TITLE
Landing page not working properly

### ISSUE THREAD

**Issue by amalvijay17** [DeviantSec/GoPhish-Templates#1]
![Screenshot](https://github.com/FreeZeroDays/GoPhish-Templates/assets/109504158/a5be3688-0e51-4c01-b1e3-18eaf436f714)
As I attached in the screenshot the image for the landing page is not working properly. Can you please fix the same?

**Comment by FreeZeroDays** [comment]
Fixed the main image disappearing with the latest commit. Looks like Microsoft rekt those links awhile back. You can find them via Wayback Machine or download from Wayback and host elsewhere. If they break again/are not to your liking I'd recommend doing the latter.
