### ISSUE TITLE
Gophish emails are going to spam folder

### ISSUE THREAD

**Issue by MohamedKarrab** [DeviantSec/GoPhish-Templates#6]
Hello man, how are you doing?
I recently got a job at a pentesting company and we do phishing campaings to certain clients, but recently using Gophish emails were going to spam folder, and I have been tasked to figure out why (they told me sent them manually and it went through, but no with Gophish). Could you provide me with any help please.

**Comment by FreeZeroDays** [comment]
Hey there. 

This is normal behavior. While out-of-scope for this repository, I would recommend doing some research into email deliverability per the GoPhish FAQ: https://docs.getgophish.com/user-guide/faq

**Comment by MohamedKarrab** [comment]
Thanks a lot, I will check them out. I have been doing research the last few days and I read a little bit about SPF, DKIM, and DMARK. I appreciate your help.
